name: Housing Regression

on: 
  push:
    branches: [ main, reg_branch, hyper_branch ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.13]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run regression pipeline
      run: |
        python regression.py
    
    - name: Run hyperparameter optimization (if on hyper_branch)
      if: github.ref == 'refs/heads/hyper_branch'
      run: python hyperparameter_tuning.py
      
    - name: Run tests
      run: |
        pytest test_regression.py -v
        pytest test_hyperparameter.py -v